# DEV Environment
instance.instances=2
instance.operatingSystem=Free: Debian, CentOS
instance.provisioningModel=Regular
instance.machineFamily=General Purpose
instance.series=n1
instance.machineType=n1-standard-4
instance.gpuType=none
instance.gpuNumber=none
instance.localSSD=1x375 GB
instance.region=Iowa (us-central1)
instance.discountOptions=Resource-based CUD - 1 year