# QA Environment
instance.instances=4
instance.operatingSystem=Free: Debian, CentOS
instance.provisioningModel=Regular
instance.machineFamily=General Purpose
instance.series=n1
instance.machineType=n1-standard-8
instance.gpuType=nvidia-tesla-p100
instance.gpuNumber=1
instance.localSSD=2x375 GB
instance.region=Netherlands (europe-west4)
instance.discountOptions=Resource-based CUD - 1 year